language: cpp  # not python!!
addons:
  apt:
    sources: deadsnakes
    packages: python3.8
before_install:
  - python3.8 --version  # Python 3.8.0
  - sudo curl https://bootstrap.pypa.io/get-pip.py | python3.8
  # ModuleNotFoundError: No module named 'distutils.util'
  - python3.8 -m pip --version || true
install: true
script: true
