language: cpp  # not python!!
matrix:
  include:
    - before_install: pyenv local 3.7.1
    - before_install: pyenv local 3.7.4
    - before_install: pyenv local 3.7.5
    - before_install: pyenv local 3.8.0
    - addons:
        apt:
          update: true
          # sources: deadsnakes
          packages:
            # - python3.8
            - python3-distutils
install:
  - pyenv version
  - pyenv install --list
  - pyenv versions || true
  - python3.8 --version  # Python 3.8.0
  - sudo curl https://bootstrap.pypa.io/get-pip.py | python3.8
  - python3.8 -m pip --version || true
script: true
