language: cpp
#env:
#  - PYTHON_VERSION="2.7"
#  - PYTHON_VERSION="2.7.14"
#  - PYTHON_VERSION="2.7.15"
#  - PYTHON_VERSION="2.7.16"
#  - PYTHON_VERSION="2.7.17"
#  - PYTHON_VERSION="3.6"
#  - PYTHON_VERSION="3.6.7"
#  - PYTHON_VERSION="3.7"
#  - PYTHON_VERSION="3.7.1"
#  - PYTHON_VERSION="3.7.2"
#  - PYTHON_VERSION="3.7.3"
#  - PYTHON_VERSION="3.7.4"
#  - PYTHON_VERSION="3.7.5"
#  - PYTHON_VERSION="3.8"
#  - PYTHON_VERSION="3.8.0"
matrix:
  include:
    - env: PYTHON_VERSION="3.8"
      addons:
        apt:
          sources: deadsnakes
          packages:
            - python3.8
      before_install:
        - pwd ; ls -R
        - curl https://bootstrap.pypa.io/get-pip.py | python3.8
        - python --version
        - pip --version || true
      install:
        - pip install flake8
        - flake8 --version
before_install:
  - pyenv install --list
  - pyenv versions
install:
  - echo ${PYTHON_VERSION} > .python-version
  - cat .python-version
  - pyenv local ${PYTHON_VERSION}
  # - pyenv global ${PYTHON_VERSION}
  # - pyenv install -v ${PYTHON_VERSION}  
script: python --version
