language: cpp  # not python!!
matrix:
  include:
    - before_install: pyenv global 3.7.1
    - before_install: pyenv global 3.7.4
    - before_install: pyenv global 3.7.5
    - before_install: pyenv global 3.8.0
    - os:osx
      before_install: pyenv global 3.8.0
    - os:osx
      before_install: pyenv global 2.7.17
    - addons:
        apt:
          update: true
          sources: deadsnakes
          packages:
            - python3.8
            # - python3-distutils
            - python3-pip
      before_install:
        - python3.8 --version  # Python 3.8.0 || true
        - sudo curl https://bootstrap.pypa.io/get-pip.py | python3.8 || true
        - python3.8 -m pip install --upgrade pip || true
        - python3.8 -m pip --version || true
        - pip3 --version || true

install:
  - pyenv commands || true
  - pyenv version
  - pyenv which python3
  - pyenv whence python3
  - pyenv which pip
  - pyenv whence pip
  - pyenv install --list
  - pyenv versions || true
script: true
