language: cpp  # not python!!
addons:
  homebrew:
    update: true
    packages:
    - pyenv
jobs:
  include:
    - before_install: pyenv global 3.7.1
    - before_install: pyenv global 3.7.4
    - before_install: pyenv global 3.7.5
    - before_install: pyenv global 3.8.0
    - os: osx
      before_install:
        - pyenv install --list
        - pyenv install 3.8.0
        - pyenv global  3.8.0
        - python3 --version ; python3 -m pip --version || true
        - python  --version ; python  -m pip --version || true
    - os: osx
         - pyenv install --list
        - pyenv install 2.7.17
        - pyenv global  2.7.17
        - python2 --version ; python2 -m pip --version || true
        - python  --version ; python  -m pip --version || true
        - ls -Fla .vendor || true
        - ls -Fla vendor  || true
    - addons:
        apt:
          update: true
          sources: deadsnakes
          packages:
            - python3.8
            # - python3-distutils
            - python3-pip
      before_install:
        - python3.8 --version  # Python 3.8.0 || true
        - sudo curl https://bootstrap.pypa.io/get-pip.py | python3.8 || true
        - python3.8 -m pip install --upgrade pip || true
        - python3.8 -m pip --version || true
        - pip3 --version || true

install:
  - pyenv commands || true
  - pyenv version
  - pyenv which python3
  - pyenv whence python3
  - pyenv which pip
  - pyenv whence pip
  - pyenv install --list
  - pyenv versions || true
script: true
