language: cpp
env:
  - PYTHON_VERSION="2.7"
  - PYTHON_VERSION="2.7.14"
  - PYTHON_VERSION="2.7.15"
  - PYTHON_VERSION="2.7.16"
  - PYTHON_VERSION="2.7.17"
  - PYTHON_VERSION="3.7"
  - PYTHON_VERSION="3.7.1"
  - PYTHON_VERSION="3.7.2"
  - PYTHON_VERSION="3.7.3"
  - PYTHON_VERSION="3.7.4"
  - PYTHON_VERSION="3.7.5"
  - PYTHON_VERSION="3.8"
  - PYTHON_VERSION="3.8.0"
before_install:
  - pyenv install --list
  - pyenv versions
install:
  # - pyenv global ${PYTHON_VERSION}
  - pyenv install -v ${PYTHON_VERSION}
script: python --version
